# Generated by Django 6.1 on 2026-09-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='uniq_zone_name_ci',
        ),
    ]
